#!/bin/bash

#PBS -l nodes=1:ppn=2,walltime=0:20:00
#PBS -N app-convert-network-netstats
#PBS -V

time singularity exec -e docker://brainlife/ga-python:lab328-dipy141-pybrainlife-1.0 ./generate-netstats.py
